{
 "title": "Cisco switch",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "target", "label": "target", "query": { "query": "label_values(target)" } },
   { "name": "DS_VICTORIAMETRICS", "query": "1" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hostname",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_facts_hostname{target=\"$target\"}",
     "legendFormat": "{{hostname}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_facts_uptime_seconds{target=\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chassis",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_facts_chassis_id{target=\"$target\"}",
     "legendFormat": "{{chassis_id}}"
    }
   ]
  },
  {
   "title": "BIOS version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_facts_bios_version{target=\"$target\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "OS Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_facts_version{target=\"$target\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total power comsume",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cisco_environment_power_in{target=\"$target\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_power_out{target=\"$target\"} / cisco_environment_power_capacity{target=\"$target\"}",
     "legendFormat": "PSU {{item}}"
    }
   ]
  },
  {
   "title": "Operational redundancy mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_power_mode{target=\"$target\", item=\"operational\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Power consumtion",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "-cisco_environment_power_in{target=\"$target\"}",
     "legendFormat": "Power in PSU {{item}}"
    },
    {
     "expr": "-sum(cisco_environment_power_in{target=\"$target\"})",
     "legendFormat": "Total power in"
    },
    {
     "expr": "cisco_environment_power_out{target=\"$target\"}",
     "legendFormat": "Power out PSU {{item}}"
    },
    {
     "expr": "sum(cisco_environment_power_out{target=\"$target\"})",
     "legendFormat": "Total power out"
    }
   ]
  },
  {
   "title": "Configured redundancy mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_power_mode{target=\"$target\", item=\"configured\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_power_capacity{target=\"$target\"}",
     "legendFormat": "PSU {{item}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_power_up{target=\"$target\"}",
     "legendFormat": "PSU {{item}}"
    }
   ]
  },
  {
   "title": "PSU efficiency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cisco_environment_power_out{target=\"$target\"}) / sum(cisco_environment_power_in{target=\"$target\"})",
     "legendFormat": "PSU efficiency"
    }
   ]
  },
  { "title": "Temperature and fan", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "cisco_environment_sensor_temp{target=\"$target\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 9, "w": 8, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_fan_up{target=\"$target\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Fan speed",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 3, "x": 21, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cisco_environment_fan_speed_percent{target=\"$target\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Transceiver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Transciver power - RX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "cisco_optics_rx{target=\"$target\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Transciver power - TX",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "cisco_optics_tx{target=\"$target\"}",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Total traffic per interface - Transmit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cisco_interface_transmit_bytes{target=\"$target\"} > 0",
     "legendFormat": "{{name}} | {{mac}} | {{description}}"
    }
   ]
  },
  {
   "title": "Total traffic per interface - Receive",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cisco_interface_receive_bytes{target=\"$target\"} > 0",
     "legendFormat": "{{name}} | {{mac}} | {{description}}"
    }
   ]
  },
  {
   "title": "Drop traffic per interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cisco_interface_receive_drops{target=\"$target\"}",
     "legendFormat": "Transmit - {{name}} | {{mac}} | {{description}}"
    },
    {
     "expr": "cisco_interface_transmit_drops{target=\"$target\"}",
     "legendFormat": "Receive - {{name}} | {{mac}} | {{description}}"
    }
   ]
  },
  {
   "title": "Traffic error per interface",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "cisco_interface_transmit_errors{target=\"$target\"}",
     "legendFormat": "Transmit - {{name}} | {{mac}} | {{description}}"
    }
   ]
  },
  { "title": "Interfaces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "type": "status-history",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "cisco_interface_admin_up{target=\"$target\", speed!=\"\"}",
     "legendFormat": "{{name}} | {{speed}}"
    }
   ]
  },
  { "title": "Etc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Collect time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "cisco_collect_duration_seconds{target=\"$target\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}